# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [5]:
### [your code here]
import numpy as np
import random



### 2. Print the NUMPY version and the configuration.


In [3]:
### [your code here]
print("Numpy version: ",np.__version__)

Numpy version:  2.1.3


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [ ]:
### [your code here]
a = np.random.random((2,3,5))


array([[[0.13900932, 0.00606436, 0.05999345, 0.53686307, 0.84612775],
        [0.25753885, 0.98879723, 0.84224472, 0.72105682, 0.10593676],
        [0.10777227, 0.82550633, 0.48357875, 0.18318852, 0.4066789 ]],

       [[0.35179784, 0.38763731, 0.25576423, 0.64755679, 0.47043012],
        [0.93803411, 0.80452243, 0.04732626, 0.24887869, 0.10919558],
        [0.04455509, 0.37085435, 0.44409107, 0.38918519, 0.87859892]]])


### 4. Print a.


In [23]:
### [your code here]
print("El arreglo generado: \n",a)

El arreglo generado: 
 [[[0.13900932 0.00606436 0.05999345 0.53686307 0.84612775]
  [0.25753885 0.98879723 0.84224472 0.72105682 0.10593676]
  [0.10777227 0.82550633 0.48357875 0.18318852 0.4066789 ]]

 [[0.35179784 0.38763731 0.25576423 0.64755679 0.47043012]
  [0.93803411 0.80452243 0.04732626 0.24887869 0.10919558]
  [0.04455509 0.37085435 0.44409107 0.38918519 0.87859892]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [ ]:
### [your code here]

b = np.ones((3,2,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])


### 6. Print b.


In [27]:
### [your code here]
print("El arreglo generado: \n",b)

El arreglo generado: 
 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [28]:
### [your code here]
print(" A y B tienen el mismo tamaño?", a.size == b.size)

 A y B tienen el mismo tamaño? True



### 8. Are you able to add a and b? Why or why not?


In [ ]:
### [your code here]
np.dot(a,b)
#Como podemos ver en el resultado del error, a pesar de tener una dimension igual, al no ser totalmente iguales no se puede realizar alguna operacion matematica,
#ya que uno es una matriz de 2x3x5 y el otro es una matriz de 3x2x5. No es posible realizar la operacion

ValueError: shapes (2,3,5) and (3,2,5) not aligned: 5 (dim 2) != 2 (dim 1)



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [30]:
### [your code here]
c = b.reshape(2,3,5)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
### [your code here]
d = a + c
""" AHORA SI FUNCIONA PUES LAS 2 TIENEN LA MISMA FORMA 2X3X5"""


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
### [your code here]
print("Valor original de A: \n",a)
print("\n")
print("Suma de A y C: \n",d)
"""
AMBAS TANTO A Y C SON COMPATIBLES PARA OPERAR
SE DIFERENCIAN DE D PUES ESTA SE OBTIENE AL SUMAR A+C, POR LO QUE SUS VALORES SON DISTINTOS, A PESAR DE TENER LA MISMA ESTRUCTURA
"""

Valor original de A: 
 [[[0.13900932 0.00606436 0.05999345 0.53686307 0.84612775]
  [0.25753885 0.98879723 0.84224472 0.72105682 0.10593676]
  [0.10777227 0.82550633 0.48357875 0.18318852 0.4066789 ]]

 [[0.35179784 0.38763731 0.25576423 0.64755679 0.47043012]
  [0.93803411 0.80452243 0.04732626 0.24887869 0.10919558]
  [0.04455509 0.37085435 0.44409107 0.38918519 0.87859892]]]


Suma de A y C: 
 [[[1.13900932 1.00606436 1.05999345 1.53686307 1.84612775]
  [1.25753885 1.98879723 1.84224472 1.72105682 1.10593676]
  [1.10777227 1.82550633 1.48357875 1.18318852 1.4066789 ]]

 [[1.35179784 1.38763731 1.25576423 1.64755679 1.47043012]
  [1.93803411 1.80452243 1.04732626 1.24887869 1.10919558]
  [1.04455509 1.37085435 1.44409107 1.38918519 1.87859892]]]



### 12. Multiply a and c. Assign the result to e.


In [35]:
### [your code here]
e = a*c



### 13. Does e equal to a? Why or why not?


In [ ]:
### [your code here]
print("La multiplicacion de AxC: \n",e)
print("\n")
print("El producto de A y E es igual?\n", a == e)

""" SON IGUALES, PUES TODOS LOS VALORES DE C SON 1"""


La multiplicacion de AxC: 
 [[[0.13900932 0.00606436 0.05999345 0.53686307 0.84612775]
  [0.25753885 0.98879723 0.84224472 0.72105682 0.10593676]
  [0.10777227 0.82550633 0.48357875 0.18318852 0.4066789 ]]

 [[0.35179784 0.38763731 0.25576423 0.64755679 0.47043012]
  [0.93803411 0.80452243 0.04732626 0.24887869 0.10919558]
  [0.04455509 0.37085435 0.44409107 0.38918519 0.87859892]]]


El producto de A y E es igual?
 [[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [40]:
### [your code here]
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("Maximo valor:",d_max)
print("\nValor Medio:",d_mean)
print("\nMinimo valor:",d_min)


Maximo valor: 1.9887972278425923

Valor Medio: 1.429959502600229

Minimo valor: 1.0060643644820586



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [45]:
### [your code here]
f = np.empty((2,3,5))
print(f)

[[[0.13900932 0.00606436 0.05999345 0.53686307 0.84612775]
  [0.25753885 0.98879723 0.84224472 0.72105682 0.10593676]
  [0.10777227 0.82550633 0.48357875 0.18318852 0.4066789 ]]

 [[0.35179784 0.38763731 0.25576423 0.64755679 0.47043012]
  [0.93803411 0.80452243 0.04732626 0.24887869 0.10919558]
  [0.04455509 0.37085435 0.44409107 0.38918519 0.87859892]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [49]:
### [your code here]
for index in np.ndindex(d.shape):
    value = d[index]
    if value == d_min:
        f[index] = 0
    elif value == d_max:
        f[index] = 100
    elif value == d_mean:
        f[index] = 50
    elif d_min < value < d_mean:
        f[index] = 25
    elif d_mean < value < d_max:
        f[index] = 75
        
print(f)
          


[[[ 25.   0.  25.  75.  75.]
  [ 25. 100.  75.  75.  25.]
  [ 25.  75.  75.  25.  25.]]

 [[ 25.  25.  25.  75.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 25.  25.  75.  25.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [ ]:
### [your code here]
print("La matriz D: \n",d)
print("\n")
print("La matriz F: \n",f)
print("\n")

""" SE CORRESPONDEN AL CODIGO POR LO QUE ES LO QUE ESPERO"""

La matriz D: 
 [[[1.13900932 1.00606436 1.05999345 1.53686307 1.84612775]
  [1.25753885 1.98879723 1.84224472 1.72105682 1.10593676]
  [1.10777227 1.82550633 1.48357875 1.18318852 1.4066789 ]]

 [[1.35179784 1.38763731 1.25576423 1.64755679 1.47043012]
  [1.93803411 1.80452243 1.04732626 1.24887869 1.10919558]
  [1.04455509 1.37085435 1.44409107 1.38918519 1.87859892]]]


La matriz F: 
 [[[ 25.   0.  25.  75.  75.]
  [ 25. 100.  75.  75.  25.]
  [ 25.  75.  75.  25.  25.]]

 [[ 25.  25.  25.  75.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 25.  25.  75.  25.  75.]]]




### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [54]:
### [your code here]

f_str = np.empty(d.shape, dtype= str)

for index in np.ndindex(d.shape):
    value = d[index]
    if value == d_min:
        f_str[index] = "A"
    elif value == d_max:
        f_str[index] = "E"
    elif value == d_mean:
        f_str[index] = "C"
    elif d_min < value < d_mean:
        f_str[index] = "B"
    elif d_mean < value < d_max:
        f_str[index] = "D"

print(f_str)



[[['B' 'A' 'B' 'D' 'D']
  ['B' 'E' 'D' 'D' 'B']
  ['B' 'D' 'D' 'B' 'B']]

 [['B' 'B' 'B' 'D' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['B' 'B' 'D' 'B' 'D']]]
